exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer
title: Raj Rajagopal
description: A personal website
github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://www.rajagopal.com"
  
title: Raj Rajagopal
description: Personal website
